/* Auto-generated by genmsg_cpp for file /home/r00t/ros_workspace/my_adaptor/srv/setFloat.srv */
#ifndef MY_ADAPTOR_SERVICE_SETFLOAT_H
#define MY_ADAPTOR_SERVICE_SETFLOAT_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "ros/service_traits.h"




namespace my_adaptor
{
template <class ContainerAllocator>
struct setFloatRequest_ {
  typedef setFloatRequest_<ContainerAllocator> Type;

  setFloatRequest_()
  : topicName()
  , newValue(0.0)
  {
  }

  setFloatRequest_(const ContainerAllocator& _alloc)
  : topicName(_alloc)
  , newValue(0.0)
  {
  }

  typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _topicName_type;
  std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  topicName;

  typedef double _newValue_type;
  double newValue;


  typedef boost::shared_ptr< ::my_adaptor::setFloatRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::my_adaptor::setFloatRequest_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct setFloatRequest
typedef  ::my_adaptor::setFloatRequest_<std::allocator<void> > setFloatRequest;

typedef boost::shared_ptr< ::my_adaptor::setFloatRequest> setFloatRequestPtr;
typedef boost::shared_ptr< ::my_adaptor::setFloatRequest const> setFloatRequestConstPtr;


template <class ContainerAllocator>
struct setFloatResponse_ {
  typedef setFloatResponse_<ContainerAllocator> Type;

  setFloatResponse_()
  : setAnswer(0.0)
  {
  }

  setFloatResponse_(const ContainerAllocator& _alloc)
  : setAnswer(0.0)
  {
  }

  typedef double _setAnswer_type;
  double setAnswer;


  typedef boost::shared_ptr< ::my_adaptor::setFloatResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::my_adaptor::setFloatResponse_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct setFloatResponse
typedef  ::my_adaptor::setFloatResponse_<std::allocator<void> > setFloatResponse;

typedef boost::shared_ptr< ::my_adaptor::setFloatResponse> setFloatResponsePtr;
typedef boost::shared_ptr< ::my_adaptor::setFloatResponse const> setFloatResponseConstPtr;

struct setFloat
{

typedef setFloatRequest Request;
typedef setFloatResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;
}; // struct setFloat
} // namespace my_adaptor

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::my_adaptor::setFloatRequest_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::my_adaptor::setFloatRequest_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::my_adaptor::setFloatRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "b1ab60507dc5afd1d1e54139f9ee670c";
  }

  static const char* value(const  ::my_adaptor::setFloatRequest_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xb1ab60507dc5afd1ULL;
  static const uint64_t static_value2 = 0xd1e54139f9ee670cULL;
};

template<class ContainerAllocator>
struct DataType< ::my_adaptor::setFloatRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "my_adaptor/setFloatRequest";
  }

  static const char* value(const  ::my_adaptor::setFloatRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::my_adaptor::setFloatRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "string topicName\n\
float64 newValue\n\
\n\
";
  }

  static const char* value(const  ::my_adaptor::setFloatRequest_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros


namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::my_adaptor::setFloatResponse_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::my_adaptor::setFloatResponse_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::my_adaptor::setFloatResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "ba18d35a4d3cea370e755997f303d718";
  }

  static const char* value(const  ::my_adaptor::setFloatResponse_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xba18d35a4d3cea37ULL;
  static const uint64_t static_value2 = 0x0e755997f303d718ULL;
};

template<class ContainerAllocator>
struct DataType< ::my_adaptor::setFloatResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "my_adaptor/setFloatResponse";
  }

  static const char* value(const  ::my_adaptor::setFloatResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::my_adaptor::setFloatResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "float64 setAnswer\n\
\n\
\n\
";
  }

  static const char* value(const  ::my_adaptor::setFloatResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::my_adaptor::setFloatResponse_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::my_adaptor::setFloatRequest_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.topicName);
    stream.next(m.newValue);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct setFloatRequest_
} // namespace serialization
} // namespace ros


namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::my_adaptor::setFloatResponse_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.setAnswer);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct setFloatResponse_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace service_traits
{
template<>
struct MD5Sum<my_adaptor::setFloat> {
  static const char* value() 
  {
    return "534d71573526d91e225c2160dfe4b29d";
  }

  static const char* value(const my_adaptor::setFloat&) { return value(); } 
};

template<>
struct DataType<my_adaptor::setFloat> {
  static const char* value() 
  {
    return "my_adaptor/setFloat";
  }

  static const char* value(const my_adaptor::setFloat&) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<my_adaptor::setFloatRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "534d71573526d91e225c2160dfe4b29d";
  }

  static const char* value(const my_adaptor::setFloatRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<my_adaptor::setFloatRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "my_adaptor/setFloat";
  }

  static const char* value(const my_adaptor::setFloatRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<my_adaptor::setFloatResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "534d71573526d91e225c2160dfe4b29d";
  }

  static const char* value(const my_adaptor::setFloatResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<my_adaptor::setFloatResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "my_adaptor/setFloat";
  }

  static const char* value(const my_adaptor::setFloatResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace service_traits
} // namespace ros

#endif // MY_ADAPTOR_SERVICE_SETFLOAT_H

