/* Auto-generated by genmsg_cpp for file /home/r00t/ros_workspace/my_adaptor/srv/setInteger.srv */
#ifndef MY_ADAPTOR_SERVICE_SETINTEGER_H
#define MY_ADAPTOR_SERVICE_SETINTEGER_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "ros/service_traits.h"




namespace my_adaptor
{
template <class ContainerAllocator>
struct setIntegerRequest_ {
  typedef setIntegerRequest_<ContainerAllocator> Type;

  setIntegerRequest_()
  : topicName()
  , newValue(0)
  {
  }

  setIntegerRequest_(const ContainerAllocator& _alloc)
  : topicName(_alloc)
  , newValue(0)
  {
  }

  typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _topicName_type;
  std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  topicName;

  typedef int64_t _newValue_type;
  int64_t newValue;


  typedef boost::shared_ptr< ::my_adaptor::setIntegerRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::my_adaptor::setIntegerRequest_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct setIntegerRequest
typedef  ::my_adaptor::setIntegerRequest_<std::allocator<void> > setIntegerRequest;

typedef boost::shared_ptr< ::my_adaptor::setIntegerRequest> setIntegerRequestPtr;
typedef boost::shared_ptr< ::my_adaptor::setIntegerRequest const> setIntegerRequestConstPtr;


template <class ContainerAllocator>
struct setIntegerResponse_ {
  typedef setIntegerResponse_<ContainerAllocator> Type;

  setIntegerResponse_()
  : setAnswer(0)
  {
  }

  setIntegerResponse_(const ContainerAllocator& _alloc)
  : setAnswer(0)
  {
  }

  typedef int64_t _setAnswer_type;
  int64_t setAnswer;


  typedef boost::shared_ptr< ::my_adaptor::setIntegerResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::my_adaptor::setIntegerResponse_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct setIntegerResponse
typedef  ::my_adaptor::setIntegerResponse_<std::allocator<void> > setIntegerResponse;

typedef boost::shared_ptr< ::my_adaptor::setIntegerResponse> setIntegerResponsePtr;
typedef boost::shared_ptr< ::my_adaptor::setIntegerResponse const> setIntegerResponseConstPtr;

struct setInteger
{

typedef setIntegerRequest Request;
typedef setIntegerResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;
}; // struct setInteger
} // namespace my_adaptor

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::my_adaptor::setIntegerRequest_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::my_adaptor::setIntegerRequest_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::my_adaptor::setIntegerRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "63fa479b4ed38f09f65f376abd1efadc";
  }

  static const char* value(const  ::my_adaptor::setIntegerRequest_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x63fa479b4ed38f09ULL;
  static const uint64_t static_value2 = 0xf65f376abd1efadcULL;
};

template<class ContainerAllocator>
struct DataType< ::my_adaptor::setIntegerRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "my_adaptor/setIntegerRequest";
  }

  static const char* value(const  ::my_adaptor::setIntegerRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::my_adaptor::setIntegerRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "string topicName\n\
int64 newValue\n\
\n\
";
  }

  static const char* value(const  ::my_adaptor::setIntegerRequest_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros


namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::my_adaptor::setIntegerResponse_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::my_adaptor::setIntegerResponse_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::my_adaptor::setIntegerResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "c45d6279501dc68282280a89f6f23997";
  }

  static const char* value(const  ::my_adaptor::setIntegerResponse_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xc45d6279501dc682ULL;
  static const uint64_t static_value2 = 0x82280a89f6f23997ULL;
};

template<class ContainerAllocator>
struct DataType< ::my_adaptor::setIntegerResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "my_adaptor/setIntegerResponse";
  }

  static const char* value(const  ::my_adaptor::setIntegerResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::my_adaptor::setIntegerResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "int64 setAnswer\n\
\n\
\n\
";
  }

  static const char* value(const  ::my_adaptor::setIntegerResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::my_adaptor::setIntegerResponse_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::my_adaptor::setIntegerRequest_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.topicName);
    stream.next(m.newValue);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct setIntegerRequest_
} // namespace serialization
} // namespace ros


namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::my_adaptor::setIntegerResponse_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.setAnswer);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct setIntegerResponse_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace service_traits
{
template<>
struct MD5Sum<my_adaptor::setInteger> {
  static const char* value() 
  {
    return "f1188add3dec534dc11668e3b8036077";
  }

  static const char* value(const my_adaptor::setInteger&) { return value(); } 
};

template<>
struct DataType<my_adaptor::setInteger> {
  static const char* value() 
  {
    return "my_adaptor/setInteger";
  }

  static const char* value(const my_adaptor::setInteger&) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<my_adaptor::setIntegerRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "f1188add3dec534dc11668e3b8036077";
  }

  static const char* value(const my_adaptor::setIntegerRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<my_adaptor::setIntegerRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "my_adaptor/setInteger";
  }

  static const char* value(const my_adaptor::setIntegerRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<my_adaptor::setIntegerResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "f1188add3dec534dc11668e3b8036077";
  }

  static const char* value(const my_adaptor::setIntegerResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<my_adaptor::setIntegerResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "my_adaptor/setInteger";
  }

  static const char* value(const my_adaptor::setIntegerResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace service_traits
} // namespace ros

#endif // MY_ADAPTOR_SERVICE_SETINTEGER_H

